# Index of Freedesktop.org Specifications

[appstream]
gitweb = "https://github.com/ximion/appstream"
externally_managed = true
docs_url="https://www.freedesktop.org/software/appstream/docs/"

[autostart]
gitweb = "https://gitlab.freedesktop.org/xdg/xdg-specs"
local = true
single_page = true
aliases = ['autostart-spec']

[basedir]
gitweb = "https://gitlab.freedesktop.org/xdg/xdg-specs"
local = true
single_page = true
aliases = ['basedir-spec']

[clipboard]
gitweb = "https://gitlab.freedesktop.org/xdg/xdg-specs"
location = "clipboard/clipboard.xml"
local = true
single_page = true
labels = ['X11']
aliases = ['clipboard-spec']

[clipboard-extensions]
gitweb = "https://gitlab.freedesktop.org/xdg/xdg-specs"
location = "clipboard/clipboard-extensions.xml"
local = true
single_page = true
labels = ['X11']
aliases = ['clipboard-extensions-spec']

[dbus]
gitweb = "https://gitlab.freedesktop.org/dbus/dbus"
externally_managed = true
docs_url="https://dbus.freedesktop.org/doc/dbus-specification.html"

[desktop-entry]
gitweb = "https://gitlab.freedesktop.org/xdg/xdg-specs"
local = true
aliases = ['desktop-entry-spec']
redirects = [
    ["ar01s02.html", "file-naming.html"],
    ["ar01s03.html", "basic-format.html"],
    ["ar01s04.html", "value-types.html"],
    ["ar01s05.html", "localized-keys.html"],
    ["ar01s06.html", "recognized-keys.html"],
    ["ar01s07.html", "exec-variables.html"],
    ["ar01s08.html", "dbus.html"],
    ["ar01s09.html", "interfaces.html"],
    ["ar01s10.html", "mime-types.html"],
    ["ar01s11.html", "extra-actions.html"],
    ["ar01s12.html", "extending.html"],
    ["apa.html", "example.html"],
    ["apb.html", "historical-items.html"],
    ["kde-items.html", "historical-items.html"],
    ["apc.html", "deprecated-items.html"],
    ["apd.html", "legacy-mixed.html"],
]

[fhs]
gitweb = "https://gitlab.freedesktop.org/FHS/fhs-spec"
local = true  # it is embedded in this repo as a submodule
project_root = "fhs"

[global-shortcuts]
gitweb = "https://gitlab.freedesktop.org/xdg/xdg-specs"
local = true
single_page = true
draft = true
aliases = ['global-shortcuts-spec']

[help-system]
gitweb = "https://gitlab.freedesktop.org/xdg/xdg-specs"
local = true
single_page = true
aliases = ['help-system-spec']

[icon-naming]
gitweb = "https://gitlab.freedesktop.org/xdg/default-icon-theme"
location = "spec/icon-naming-spec.xml"
single_page = true
aliases = ['icon-naming-spec']

[icon-theme]
gitweb = "https://gitlab.freedesktop.org/xdg/default-icon-theme"
location = "spec/icon-theme-spec.xml"
single_page = true
aliases = ['icon-theme-spec']

[idle-inhibit]
gitweb = "https://gitlab.freedesktop.org/xdg/xdg-specs"
local = true
single_page = true
location = "idle-inhibit/specification.xml"
project_root="idle-inhibit"
aliases = ['idle-inhibit-spec']

[menu]
gitweb = "https://gitlab.freedesktop.org/xdg/xdg-specs"
local = true
location = "menu/menu-spec.xml"
aliases = ['menu-spec']
redirects = [
    ["ar01s02.html", "paths.html"],
    ["ar01s03.html", "desktop-entry-extensions.html"],
    ["ar01s04.html", "menu-file-format.html"],
    ["ar01s05.html", "merge-algorithm.html"],
    ["ar01s06.html", "query-algorithm.html"],
    ["ar01s07.html", "legacy-hierarchies.html"],
    ["ar01s08.html", "example.html"],
    ["apa.html", "category-registry.html"],
    ["apas02.html", "additional-category-registry.html"],
    ["apas03.html", "reserved-category-registry.html"],
    ["apb.html", "onlyshowin-registry.html"],
    ["apc.html", "third-party-howto.html"],
    ["apcs02.html", "locations.html"],
    ["apcs03.html", "menu-add-example.html"],
    ["apcs04.html", "compatibility.html"],
    ["apd.html", "implementation-notes.html"],
]

[mime-apps]
gitweb = "https://gitlab.freedesktop.org/xdg/xdg-specs"
local = true
location = "mime-apps/mime-apps-spec.xml"
aliases = ['mime-apps-spec']

[mpris]
gitweb = "https://gitlab.freedesktop.org/mpris/mpris-spec"
local = true  # it is embedded in this repo as a submodule
project_root = "mpris"
aliases = ['mpris-spec']

[notification]
gitweb = "https://gitlab.freedesktop.org/xdg/xdg-specs"
local = true
location = "notification/notification-spec.xml"
aliases = ['notification-spec']
redirects = [
    ["ar01s02.html", "basic-design.html"],
    ["ar01s03.html", "backwards-compat.html"],
    ["ar01s04.html", "markup.html"],
    ["ar01s05.html", "icons-and-images.html"],
    ["ar01s06.html", "categories.html"],
    ["ar01s07.html", "urgency-levels.html"],
    ["ar01s08.html", "hints.html"],
    ["ar01s09.html", "protocol.html"],
]

[polkit]
gitweb = "https://gitlab.freedesktop.org/polkit/polkit"
externally_managed = true
docs_url="https://www.freedesktop.org/software/polkit/docs/latest/"

[recent-files]
gitweb = "https://gitlab.freedesktop.org/xdg/xdg-specs"
local = true
single_page = true
location = "recent-files/recent-file-spec.xml"
aliases = ['recent-files-spec']

[secret-service]
gitweb = "https://gitlab.freedesktop.org/xdg/xdg-specs"
local = true
location = "secret-service/specification.xml"
aliases = ['secret-service-spec']

[shortcuts]
gitweb = "https://gitlab.freedesktop.org/xdg/xdg-specs"
local = true
single_page = true
draft = true
aliases = ['shortcuts-spec']

[shared-mime-info]
gitweb = "https://gitlab.freedesktop.org/xdg/shared-mime-info"
location = "data/shared-mime-info-spec.xml"
aliases = ['shared-mime-info-spec']

[sound-naming]
gitweb = "https://gitlab.freedesktop.org/xdg/sound-theme-spec"
location = "spec/sound-naming-spec.xml"
single_page = true
aliases = ['sound-naming-spec']

[sound-theme]
gitweb = "https://gitlab.freedesktop.org/xdg/sound-theme-spec"
location = "spec/sound-theme-spec.xml"
aliases = ['sound-theme-spec']
redirects = [
    ["ar01s02.html", "definitions.html"],
    ["ar01s03.html", "directory_layout.html"],
    ["ar01s04.html", "file_formats.html"],
    ["ar01s05.html", "sound_lookup.html"],
    ["ar01s06.html", "example.html"],
    ["ar01s07.html", "install_sounds.html"],
    ["ar01s08.html", "implementation_notes.html"],
    ["ar01s09.html", "background.html"],
    ["apa.html", "changes.html"],
]

[startup-notification]
gitweb = "https://gitlab.freedesktop.org/xdg/startup-notification"
location = "doc/startup-notification.xml"
aliases = ['startup-notification-spec']

[status-notifier-item]
local = true
gitweb = "https://gitlab.freedesktop.org/xdg/xdg-specs"
location = "status-notifier-item/status-notifier-item-spec.xml"
draft = true

[systemtray]
gitweb = "https://gitlab.freedesktop.org/xdg/xdg-specs"
local = true
location = "systemtray/systemtray-spec.xml"
aliases = ['systemtray-spec']
labels = ['X11']

[thumbnail]
gitweb = "https://gitlab.freedesktop.org/xdg/xdg-specs"
local = true
location = "thumbnail/thumbnail-spec.xml"
aliases = ['thumbnail-spec']

[trash]
gitweb = "https://gitlab.freedesktop.org/xdg/xdg-specs"
local = true
format = "sphinx"

[wm]
gitweb = "https://gitlab.freedesktop.org/xdg/xdg-specs"
local = true
location = "wm/wm-spec.xml"
aliases = ['wm-spec']
labels = ['X11']

[xembed]
gitweb = "https://gitlab.freedesktop.org/xdg/xdg-specs"
local = true
location = "xembed/spec/xembed-spec.xml"
aliases = ['xembed-spec']
labels = ['X11']

[xsettings]
gitweb = "https://gitlab.freedesktop.org/xdg/xdg-specs"
local = true
make_commands = []
location = "xsettings/xsettings.xml"
single_page = true
aliases = ['xsettings-spec']
labels = ['X11']
