xdg_config_home(7)

# NAME

xdg_config_home - XDG base directory for user-specific configuration files

# DESCRIPTION

*$XDG_CONFIG_HOME* defines the base directory relative to which user-specific
configuration files should be stored.

# DEFAULT

If *$XDG_CONFIG_HOME* is either not set or empty, a default equal to
_$HOME/.config_ should be used.

# SEE ALSO

*basedir-spec*(7), *xdg_config_dirs*(7)
